apiVersion: v1
kind: Service
metadata:
  name: scale-predictor-service
spec:
  clusterIP: None  # Headless Service
  selector:
    app: scale-predictor  
  ports:
    - name: scale-predictor-service
      port: 50051 
      targetPort: 50051 
  #     nodePort: 30051
  # type: NodePort