# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scale_predictor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scale_predictor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scale_predictor.proto\x12\x0fscale_predictor\"F\n\x0ePredictRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0e\n\x06window\x18\x02 \x03(\x01\x12\r\n\x05index\x18\x03 \x01(\x05\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\"=\n\x0cLearningPair\x12\x14\n\x0cinput_window\x18\x01 \x03(\x01\x12\x17\n\x0f\x65xpected_output\x18\x02 \x01(\x01\"[\n\x0cTrainRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x34\n\rlearning_data\x18\x02 \x03(\x0b\x32\x1d.scale_predictor.LearningPair\"4\n\rTrainResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"@\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x13\n\x0bwindow_size\x18\x03 \x01(\x05\"/\n\x0bTrainStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf1\x01\n\x0eScalePredictor\x12L\n\x07Predict\x12\x1f.scale_predictor.PredictRequest\x1a .scale_predictor.PredictResponse\x12\x46\n\x05Train\x12\x1d.scale_predictor.TrainRequest\x1a\x1e.scale_predictor.TrainResponse\x12I\n\x0bTrainByFile\x12\x1a.scale_predictor.FileChunk\x1a\x1c.scale_predictor.TrainStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scale_predictor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=42
  _globals['_PREDICTREQUEST']._serialized_end=112
  _globals['_PREDICTRESPONSE']._serialized_start=114
  _globals['_PREDICTRESPONSE']._serialized_end=147
  _globals['_LEARNINGPAIR']._serialized_start=149
  _globals['_LEARNINGPAIR']._serialized_end=210
  _globals['_TRAINREQUEST']._serialized_start=212
  _globals['_TRAINREQUEST']._serialized_end=303
  _globals['_TRAINRESPONSE']._serialized_start=305
  _globals['_TRAINRESPONSE']._serialized_end=357
  _globals['_FILECHUNK']._serialized_start=359
  _globals['_FILECHUNK']._serialized_end=423
  _globals['_TRAINSTATUS']._serialized_start=425
  _globals['_TRAINSTATUS']._serialized_end=472
  _globals['_SCALEPREDICTOR']._serialized_start=475
  _globals['_SCALEPREDICTOR']._serialized_end=716
# @@protoc_insertion_point(module_scope)
