# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scale_predictor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scale_predictor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scale_predictor.proto\x12\x0fscale_predictor\"F\n\x0ePredictRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0e\n\x06window\x18\x02 \x03(\x05\x12\r\n\x05index\x18\x03 \x01(\x05\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32^\n\x0eScalePredictor\x12L\n\x07Predict\x12\x1f.scale_predictor.PredictRequest\x1a .scale_predictor.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scale_predictor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=42
  _globals['_PREDICTREQUEST']._serialized_end=112
  _globals['_PREDICTRESPONSE']._serialized_start=114
  _globals['_PREDICTRESPONSE']._serialized_end=147
  _globals['_SCALEPREDICTOR']._serialized_start=149
  _globals['_SCALEPREDICTOR']._serialized_end=243
# @@protoc_insertion_point(module_scope)
